[env:uno]
platform  = atmelavr
board     = uno
framework = arduino

; Velocidade do monitor serial
monitor_speed = 9600

; Velocidade de upload
upload_speed = 115200

; Limpa o terminal ao iniciar o monitor
monitor_filters = send_on_enter, colorize

; Build flags: altere LIMITE_SECO aqui sem tocar no código
build_flags =
    -D LIMITE_SECO=600
    -D HISTERESE=50
    -D TEMPO_MAX_BOMBA=30000
    -D INTERVALO_LEITURA=1000
    -D DEBUG_MODE=1